## Lesson 5 Numpy

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,2.1])
arr1 

array([1. , 2. , 2.1])

In [4]:
arr2 = np.array([1,2,'a'])
arr2

array(['1', '2', 'a'], dtype='<U21')

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.array([[1,2,3],[3,4,5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
arr3 = np.array([1,2,3], dtype=int)
arr3 

array([1, 2, 3])

In [13]:
arr3.dtype 

dtype('int64')

In [14]:
arr3[1]

np.int64(2)

In [15]:
arr3[1]=4
arr3

array([1, 4, 3])

In [16]:
arr3[2] = 5.14
arr3 

array([1, 4, 5])

In [17]:
arr3.nbytes

24

In [18]:
arr2.nbytes

252

In [23]:
x1 = np.random.randint(10, size=7)
x1 

array([9, 2, 4, 5, 9, 4, 8], dtype=int32)

In [24]:
x1[:3]

array([9, 2, 4], dtype=int32)

In [25]:
x1[-1]

np.int32(8)

In [21]:
x2 = np.random.randint(10, size=(3, 4))
x2 

array([[9, 0, 1, 6],
       [6, 2, 9, 5],
       [8, 1, 6, 0]], dtype=int32)

In [26]:
x2[0,0]

np.int32(9)

In [27]:
x2[0,:]

array([9, 0, 1, 6], dtype=int32)

In [28]:
x2[:,0]

array([9, 6, 8], dtype=int32)

In [29]:
x2[:2,:2]

array([[9, 0],
       [6, 2]], dtype=int32)

In [30]:
x2

array([[9, 0, 1, 6],
       [6, 2, 9, 5],
       [8, 1, 6, 0]], dtype=int32)

In [31]:
x1 

array([9, 2, 4, 5, 9, 4, 8], dtype=int32)

In [34]:
sub_x1 = x1[:2]
sub_x1 

array([9, 2], dtype=int32)

In [35]:
sub_x1[0] =999
print(sub_x1)
print(x1)


[999   2]
[999   2   4   5   9   4   8]


In [36]:
a=[1,2,3]
b = a[:2]
b 

[1, 2]

In [37]:
b[0] =999
print(b)
print(a)

[999, 2]
[1, 2, 3]


In [40]:
x1.append(arr1)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [42]:
np.append(x1, arr1)

array([999. ,   2. ,   4. ,   5. ,   9. ,   4. ,   8. ,   1. ,   2. ,
         2.1])

In [43]:
x1 

array([999,   2,   4,   5,   9,   4,   8], dtype=int32)

In [46]:
np.insert(x1,[2,4],400)

array([999,   2, 400,   4,   5, 400,   9,   4,   8], dtype=int32)

In [47]:
x1 

array([999,   2,   4,   5,   9,   4,   8], dtype=int32)

In [48]:
len(x1)

7

In [49]:
x1.shape

(7,)

In [50]:
x = np.arange(1,21)
x 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
y = x.reshape(4,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
y.size 

20

In [54]:
x.size 

20

In [56]:
x.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [57]:
x.reshape((2,5,-1))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [58]:
x.reshape(5,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [59]:
x.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [60]:
y 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
y.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
y.flatten().shape

(20,)

In [68]:
y.reshape(-1,20).shape

(1, 20)

In [69]:
a = np.full((2,3),1)
b = np.full((2,3),9)
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[9 9 9]
 [9 9 9]]


In [70]:
np.concatenate([a,b],axis = 0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [71]:
np.concatenate([a,b],axis = 1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [72]:
np.concatenate([a,b],axis = None)

array([1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9])

In [3]:
import numpy as np 
big_arr = np.arange(10**9)
big_arr

array([        0,         1,         2, ..., 999999997, 999999998,
       999999999])

In [ ]:
#%timeit sum(big_arr)

In [4]:
%timeit np.sum(big_arr)

778 ms ± 109 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
np.random.seed(0)
c = np.random.randint(10, size=(3,4))
c 

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [12]:
(c>3).sum()
np.sum(c>3)

np.int64(7)

In [13]:
c 

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [15]:
np.sum(c, axis=None)

np.int64(54)

In [16]:
np.sum(c, axis=0)

array([14, 13, 13, 14])

In [17]:
np.sum(c, axis=1)

array([11, 24, 19])

In [20]:
c<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [23]:
np.sum(c<6,axis= 1)

array([4, 2, 2])

In [24]:
from my_module import is_prime

In [25]:
c.shape

(3, 4)

In [28]:
list(map(lambda x: x+1, [1,2,3,4]))

[2, 3, 4, 5]

In [29]:
list(map(is_prime, [1,2,3,4]))

[False, True, True, False]

In [31]:
c 

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [36]:
mask = np.array(list(map(is_prime, c.flatten()))).reshape(c.shape)
np.sum(c[mask])

np.int64(35)

In [42]:
c[[0,2],[0,1]]  

array([5, 4], dtype=int32)

In [45]:
a = np.array([[10,40],
             [30,20]])
a 

array([[10, 40],
       [30, 20]])

In [49]:
np.sort(a, axis=1)

array([[10, 40],
       [20, 30]])

In [48]:
np.sort(a, axis=0)

array([[10, 20],
       [30, 40]])

In [46]:
np.sum(a, axis=0)

array([40, 60])

In [47]:
np.sort(a, axis=None)

array([10, 20, 30, 40])

In [50]:
arr = np.array([2,6,2,1,4])

In [51]:
np.sort(arr)

array([1, 2, 2, 4, 6])

In [52]:
np.argsort(arr)

array([3, 0, 2, 4, 1])

In [53]:
arr[np.argsort(arr)]

array([1, 2, 2, 4, 6])